### ISSUE TITLE
Typo in CppUMock manual

### ISSUE THREAD

**Issue by terop** [cpputest/cpputest.github.io#23]
There is a typo in the MyTypeComparator example code. Specifically on the line:
`virtual SimpleString valueToString(cont void* object)`. I assume that `cont` should be `const`.
I am aware that this is a minor issue but it could still be fixed. I can make a PR if it is necessary.

**Comment by basvodde** [comment]
A PR would be great.

**Comment by terop** [comment]
PR: https://github.com/cpputest/cpputest.github.io/pull/24

**Comment by basvodde** [comment]
Thanks!
